version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    reviewers:
      - "frc-862/reviewers"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[#1] "
    labels:

