name:  Simulate Code

on:
    pull_request:
    
jobs:
    simulateJava:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout and Initialize Thunder
              uses: actions/checkout@v3
              with:
                submodules: 'true'
            - name: Init JDK
              uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: '17'
            - name: Set Execution Permissions
              run: chmod +x ./gradlew && chmod +x .github/sim_timeout.sh
            - name: Simulate Code
              run: .github/sim_timeout.sh
            # - name: Kill Java Processes
            #   run: pkill -f 'java'
            # - name: Archive Simulation Results
            #   uses: actions/upload-artifact@v3
            #   with:
            #     name: simulation-results
            #     path: build/reports/**