name: Simulate Code

on:
    push:
        branches:
            - 93-github-actions-robot-simulate
    
jobs:
    simulate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set Execution Permissions
              run: chmod +x ./gradlew
            - name: Simulate Code
              run: ./gradlew simulate

